name: salam-go
version: '0.0.1'
# grade: devel
grade: stable
summary: Say Salam
description: |
    Just say Salam
    From a Go app

base: core22

# confinement: devmode
confinement: strict

parts:
    salam-go:
        plugin: dump
        source: .

apps:
    salam-go:
        command: salam-go
        plugs: [network, home]
